### ISSUE TITLE
Print paper wallets and make sure setup process works as expected

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#1]
## Scope

<img width="965" alt="Screen Shot 2019-07-16 at 13 50 44" src="https://user-images.githubusercontent.com/2758453/61292134-bac4b300-a7d0-11e9-9609-98a6f8a6d5ff.png">

- Players will be on-boarded to the game by scanning a QR code on a paper wallet that was handed to them by an organizer
- The paper wallet needs to contain:
  - instructions on how to us the paper wallet in combination with the phone
  - a *prefunded* valid Ethereum address
  - a private key that allows a burner-wallet to be bootstrapped
  - 
- From BlockSplit, LeapDAO has already forked and modified a version of Austin Griffith's paper wallet generator here: https://github.com/leapdao/paper-wallet

## Deliverables

- Modify the leapdao/paper-wallet to generate the "Ethereum Meetup 24. July" paper wallet and preload them with the relevant currency (Goellars?)
- Make test scans with the social-dist0rtion-protocol/toco2-burner-wallet and make sure that all scanning works as expected. Fix any occurring bugs or file appropriate issues
- It is **not** necessary to make this version of the paper-wallet especially fancy due to time constraints!

## Note

The upstream leapdao/plasma-burner-wallet currently has a bug when withdrawing funds from a private key (https://github.com/leapdao/plasma-burner-wallet/issues/216). It might be that this bug is circumventing to launch a burner-wallet from a paper wallet. It might also not. Please take note.

## Gains for the project

- Streamlined on-boarding process for the users
- Sybil-resistant process to on-board users (1 player = 1 wallet)

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
@eshavkun would work on this
