### ISSUE TITLE
deploy tokens and enable spending conditions on mainnet

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#101]
## Scope

- deploy collateralizable goellars contract
- deploy CO2 contnract
- deploy 6 enumerable ERC1949 contracts

## Deliverables
- registered tokens 
- enabled spending conditions 

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
@johannbarbie can we close this as we're shipping to testnet?

**Comment by TimDaub** [comment]
Optimistically closing. Feel free to reopen.
