### ISSUE TITLE
Implement Planet A themed burner-wallet

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#11]
[TODO]

**Comment by MaxStalker** [comment]
I decided to give it a go and try to draft something. Here's what I have so far. Let me know if I shall continue to work on this or simply scrap it :)
![PlanetA - Main Screen](https://user-images.githubusercontent.com/3136647/61468384-da510c80-a985-11e9-9800-d0aae6aa6ee1.jpg)

**Comment by TimDaub** [comment]
Woah this looks super cool man!
