### ISSUE TITLE
Map passports to passport id

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#110]

**Comment by TimDaub** [comment]
Can be solved by mapping name to passport id.

**Comment by TimDaub** [comment]
## Scope

- @micheleb has generate a bunch of names here: https://github.com/social-dist0rtion-protocol/planet-a-dashboard/blob/master/names.json
- @eshavkun has generated all the private keys + addresses for the paper wallets
- In the wallet, when clicking on a passport, a player's name is shown

## Deliverables

- Map a passport's id to a player's name and display it in the UI
- You'll probably have to talk to @micheleb or @eshavkun for the list of names to passport ids

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by micheleb** [comment]
these are all the mappings from ccc => https://github.com/social-dist0rtion-protocol/planet-a-backend/blob/master/src/players.json
I'm waiting for the addresses for ethberlin2 to fill the rest

**Comment by micheleb** [comment]
complete list available at https://github.com/social-dist0rtion-protocol/planet-a-backend/blob/master/src/players.json
