### ISSUE TITLE
smth wrong, pls tell us

### ISSUE THREAD

**Issue by ligi** [social-dist0rtion-protocol/planet-a#132]
see here:

![image](https://user-images.githubusercontent.com/111600/63621536-752baf00-c5f4-11e9-988d-01ae0e7e28f2.png)

I told u and the theory is that the problem is rooted in the fact I already played the game when you did the talk/betatest at c-base. You suggested to open an issue: done ;-)

**Comment by TimDaub** [comment]
@ligi can u post your address somehow? I can add your name manually :)

**Comment by ligi** [comment]
sure thing that: 0xa6ae5bfe0032b2a8baf9fef9dd46f7d45916d6b1
