### ISSUE TITLE
Move "Handshake" and "Plant Tree" under passport view

### ISSUE THREAD

**Issue by MaxStalker** [social-dist0rtion-protocol/planet-a#21]
# Scope
Right now "Handshake" and "Trade" buttons are placed outside of the passports, though both of them tied to a currently selected passport. And if none of the passports is selected, player should not be able to do any of those actions.

# Deliverables

- Move those two functions inside passport
- Refactor code that relied on active passport 

# Notes
**Pros:**
- it's always clear which citizen is doing the action, so if i'm multi-pass citizen I can be a Mr. Green in one country and aggresive CO2 producer in another 😱
- better coder experience - a bit less props drilling and utility methods to extract current passport

**Cons:**
- that functionality is a bit hidden, though if you have a single passport (like most of the people gonna have) - then we can open passport view right away

# Roles
bounty gardener: @MaxStalker / 10%
bounty worker: @MaxStalker  / 75%
bounty reviewer: name / 15%

**Comment by vrde** [comment]
> that functionality is a bit hidden, though if you have a single passport (like most of the people gonna have) - then we can open passport view right away

I think this is crucial in terms of usability. During the meetup players didn't know you can tap on the passport. If we open it by default, we would solve this issue.
