### ISSUE TITLE
handshake with Prisoner's Dilemma

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#33]

**Comment by vrde** [comment]
# Scope
To make the game spicier, each handshake should be an instance of the prisoner's dilemma. 

In the following diagram you can see the interaction matrix between Player 1 and Player 2. Each player can *collaborate* or *defect* the other player.

![image](https://user-images.githubusercontent.com/134680/62823669-abe4dc80-bb93-11e9-83e9-de8871164610.png)

Player 1 is the one that starts the handshake by showing their QRCode to Player 2. The possibilities are:
- P1 collaborates and P2 collaborates:
  - P1 gets a *medium* reward in Göllars
  - P1 emits a *low* amount of CO₂
  - P2 gets a *medium* reward in Göllars
  - P2 emits a *low* amount of CO₂
- P1 defects and P2 collaborates:
  - P1 gets a *high* reward in Göllars
  - P1 emits a *high* amount of CO₂
  - P2 gets a *low* reward in Göllars
  - P2 emits a *high* amount of CO₂
- P1 collaborates and P2 defects:
  - P1 gets a *low* reward in Göllars
  - P1 emits a *low* amount of CO₂
  - P2 gets a *high* reward in Göllars
  - P2 emits a *high* amount of CO₂
- P1 defects and P2 defects:
  - P1 gets a *low* reward in Göllars
  - P1 emits a *high* amount of CO₂
  - P2 gets a *low* reward in Göllars
  - P2 emits a *high* amount of CO₂

Rewards and emissions are managed by the `Earth` contract and described in the issue https://github.com/social-dist0rtion-protocol/planet-a-contracts/issues/4.

# Deliverable
- Update the UI to support *collaborate* and *defect* actions.
- Add enough information to the UI to make the thing understandable to the average user.
- Update the code to make the burner wallet work with the new contract.

# Roles
- Gardener: @vrde / 5%
- Worker: @vrde / 70%
- Reviewer: @MaxStalker  / 25%
