### ISSUE TITLE
consolidate CO2 on Air contract

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#35]

**Comment by troggy** [comment]
also needs to be done in Earth contract. Will require some service with Game Master key

**Comment by vrde** [comment]
I've created the issue in the smart contract repo: social-dist0rtion-protocol/planet-a-contracts#13

**Comment by TimDaub** [comment]
> I've created the issue in the smart contract repo: [social-dist0rtion-protocol/planet-a-contracts#13](https://github.com/social-dist0rtion-protocol/planet-a-contracts/issues/13)

OK. Closing
