### ISSUE TITLE
Consolidate UTXOs in user's wallet when more than X

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#36]

**Comment by TimDaub** [comment]
## Scope and Deliverables

- This issue explains the scope and deliverables: https://github.com/leapdao/plasma-burner-wallet/issues/106



## Roles: 
bounty gardener: @TimDaub / 10% 
bounty worker: name / 75% 
bounty reviewer: name / 15% 

## Note

You'll receive SDP tokens as a worker/reviewer on this issue. SDP will receive DAI in their multi sig once you've successfully completed your PR upstream.


## Funded by
- [LeapDAO's ecosystem circle (DAI)](https://github.com/social-dist0rtion-protocol/planet-a/issues/49#issuecomment-517745038)
- SDP multisig (SDP)
