### ISSUE TITLE
Simulate Ethereum Meetup and deliver possible configurations; Make configuration simple

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#4]
## Scope

- "Planet A"'s duration is dependent on the configurable values that its developers set before launching the game
- If everybody's coordinating perfectly around their CO2 emissions, the game could potentially last "forever"
- Similarly, if nobody's coordinating, the game could be very short lived.
- The idea then is to find parameters that allow "a strong outcome" for all players. Drama should be created! E.g. "Game lasts for an hour but then everybody gets fucked quickly" => lose or "Game lasts for an hour and players almost wreck the world but then start coordinating correctly" => win
- At this stage of course, we can't know *how* users are gonna play the game though. So simulating too much possibly won't yield better results.

## Deliverables

- Do some rough research on how large the Ethereum meetup will be and how many participants will likely engage in a game like this
- Based on the above: Recommend a set of parameters for the game that is played at the Ethereum meetup
- Additionally, make adjusting parameters really easy such that experimentation can happy without friction:
  - put all values in files like config.js
  - Make all contracts easily deployable and changeable
  - etc.

## Gains for the project

- Quick experimentation of game mechanics by adjusting the game's parameters and playing more games
- Potential to adjust parameters mid-game and the opportunity to watch players adjust to newly created game environment

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by vrde** [comment]
Overlaps with #16 that is almost delivered. What is still relevant is:

> Additionally, make adjusting parameters really easy such that experimentation can happy without friction
