### ISSUE TITLE
theme burner wallet for ethBerlin and cccamp

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#40]

**Comment by TimDaub** [comment]
## Scope

- The Planet A wallet uses a theme.js file and the rimble-ui package to style it's components
- In theory, the styling of the wallet should easily be adjusted by changing various color values in config and theme files
- At the Ethereum meetup in July, we had already themed the wallet by giving buttons and other UI elements "arbitrary" colors
- As the game will be exclusively be played at ETHBerlinZwei and cccamp19, we're now realizing that we'd like to submit ourselves to the events "design identity"
- @MaxStalker has done an amazing job already in coming up with a cool theme and structure on how the wallet should look like. Of particular interest is [this issue](https://github.com/social-dist0rtion-protocol/planet-a/issues/11#issuecomment-512853319) and the result over at planeta.leap.rocks.

![image](https://user-images.githubusercontent.com/2758453/62380947-aa3f6700-b54a-11e9-92b7-6b7a9ad6e42f.png)


## Deliverables

- Take a look at the design of https://ethberlinzwei.com/ and the respective pendant of cccamp19
- Option A:
  - Come up with a theme that respects and embraces the EthBerlinZwei **but also* the cccamp19 design concept. So we'd mix the two.
- Option B:
  - Implement a dynamic theme switcher that allows us to have a cccamp theme and a EthBerlin theme that can be switched based on e.g. urls
- Option C etc.: Come up with a better strategy and implement it as part of this issue

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
@MaxStalker please let me know if you'd like to take this issue over (as discussed on Slack).

**Comment by MaxStalker** [comment]
@TimDaub Totally! :)

**Comment by TimDaub** [comment]
More resources for theming the burner:

Proposed logo: https://media.giphy.com/media/TGpIDTOleEBa882QBd/giphy.gif

We're gonna add 6 colors for passports:
- The three from EthBerlinZwei
- And the three from the camp: https://events.ccc.de/2019/07/09/design-release-chaos-communication-camp-2019/
