### ISSUE TITLE
integrate the dashboard into ethBerlinZwei screens

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#41]

**Comment by vrde** [comment]
# Scope
- Screens/projectors will be used during EthBerlinZwei to keep attendees up to date with the status of the conference, like next talks in line, and more.
- Planet A has a super cool dashboard that displays stats about the environment. Those stats help participants to understand how the simulation is going, and act accordingly.
- We don't know exactly how screens are used, and how many of them are there.
- We have to talk to the organizers and understand how we can plug Planet A dashboard in their system.

# Deliverables
- Strategy and code to display Planet A dashboard during EthBerlinZwei.

# Roles
- Gardener: @vrde / 10%
- Worker: ? / 75%
- Reviewer: ? / 15%

**Comment by TimDaub** [comment]
@micheleb and @vrde: Since @micheleb has created three more descriptive issues, can we close this issue?

**Comment by micheleb** [comment]
Actually I'd leave this open, as this is about doing whatever's needed to show the dashboard on EthBerlinZwei monitors (which might involve taking screenshots at regular intervals, upload stuff somewhere, whatever)

**Comment by micheleb** [comment]
and I guess this can be closed now, as they said this:

> Hi Griffin, Hi Alberto, 
> 
> Could you please tell us more about what will happen in the crypto economics room? 
> You have one screen in the room, on which you can play what you like. For all the other screens in the building content is already planned and a stream is not possible. 
> 
> Best, 
> 
> Nataly

so... it's gonna be just an HDMI cable
