### ISSUE TITLE
Bring back Exchange.js to allow Goellars off-boarding

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#42]
1. allow people to lock DAI on mainnet to deposit goellars.
2. enable exchange view, and allow people to fast exit goellars to DAI

<img width="765" alt="Screen Shot 2019-08-12 at 6 23 25 PM" src="https://user-images.githubusercontent.com/659301/62880899-c30c0180-bd2e-11e9-830d-358d80acd91a.png">

**Comment by TimDaub** [comment]
## Scope

- peep.cash has an Exchange.js
- We need to allow depositing DAI for Goellars and we need to allow off-boarding of Goellars for DAI using a market maker

## Deliverables

- Bring back Exchange.js and adjust it such that it allows the above functionality

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
In Slack we've concluded that we'll ship to testnet, so I'll close optimistically. Feel free to reopen if needed.
