### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#44]
# Bounty

## Scope
Automatic continuous deployment has to be set up for the game.

## Deliverables
Travis configuration script that allows for CI deployment.
All required environment variables to be set in the settings.
Deployment to perform on push to the master branch.

## Gain for the project
Quick automatic deployment is always good - it simplifies work and provides extra stability.

### Publicly visible delivery
Publicly not visible.

## Roles
bounty gardener: @articobandurini / 10%
bounty worker: @articobandurini / 75%
bounty reviewer: @johannbarbie / 15%

**Comment by art1c0** [comment]
Fixed with https://github.com/social-dist0rtion-protocol/planet-a/pull/120
