### ISSUE TITLE
fix commas and periods in amount field upstream

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#47]

**Comment by TimDaub** [comment]
## Scope

- Currently, the burner wallet uses the i18n package to do localization
- We're about to use react-i18next: https://github.com/leapdao/plasma-burner-wallet/pull/195
- Try the following on your burner-wallet:
  - Depending on your browser language, try sending an amount of money with decimals but alternate between a period `.` and a comma `,`. So in the SendToAddress.js view try putting into the `<Input />` `2.5` or `2,5`.
- You'll notice that often decimal values but particular their delimiter (so commas or periods) will bug the process

## Deliverables

- Fix this issue upstream (leapdao/plasma-burner-wallet)
- Then create a PR to fix this issue also in this repo
- Make sure that you test various languages that prefer commas over periods and vice versa

## Note

It might make sense to get in contact with @MaxStalker and/or @iamonuwa as they've already done some work on this topic and might know more!  

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by iamonuwa** [comment]
I would love to work on this. As I already implemented it on burner. I'll rebase both

**Comment by TimDaub** [comment]
@iamonuwa I unassigned you from here as I remember you mentioned that you won't do it, correct?

**Comment by iamonuwa** [comment]
Right

**Comment by TimDaub** [comment]
Fixed in #118
