### ISSUE TITLE
Fix swiping PDAI

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#49]

**Comment by TimDaub** [comment]
## Scope and Deliverables

- Details here: https://github.com/leapdao/plasma-burner-wallet/issues/216
- Additionally: Take PR from upstream and have it merged and reviewed here 

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

## Note

You'll receive SDP tokens as a worker/reviewer on this issue. SDP will receive DAI in their multi sig once you've successfully completed your PR upstream.


## Funded by
- [LeapDAO's ecosystem circle (DAI)](https://github.com/social-dist0rtion-protocol/planet-a/issues/49#issuecomment-517745038)
- SDP multisig (SDP)

**Comment by TimDaub** [comment]
Removed bounty tag from this. We're not gonna invoice as it was a one-liner
