### ISSUE TITLE
Implement Trade view

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#5]
## Scope

<img width="958" alt="Screen Shot 2019-07-16 at 14 26 36" src="https://user-images.githubusercontent.com/2758453/61294278-bea70400-a7d5-11e9-8c55-dedad5a1622f.png">

- In "Planet A" two players can trade.
- A trade emits CO2
- CO2 is tracked on a per-player basis. Essentially each player will have a CO2 score
- The trading process works as follows:
  - Two players (A and B) meet in real life and talk about the game
  - Player A asks Player B to trade within the game
  - To initiate the trade, Player A selects "trade" from their wallet. The wallet generates a QR code
  - If Player B decides to accept the trade of Player A, then some goods are exchanged between the two, CO2 is globally emitted ("into the air") and also credited to their individual balance

 ### "Mechanics"

- From the testing a light version of the game, it became clear that the following things make trading more fun:
  - knowing the other players Goellars, Plants and CO2 balance
  - being able to assume how the other player got their Goellars, Plants, CO2 (e.g. do some players wash their balances green?)
  - Players shouldn't constantly be able to trade. Instead there should be a cool down. If that turns out to be difficult to implement within the time frame of the Ethereum meetup, a simple frontend block might be sufficient to test the idea

## Deliverables

- Build a trade view according to the specifications above

## Note

- The trade view will be one of the first views, we want a user to explore. It should hence be "easily accessible" to the user in terms of usability. Meaning it should be simple and "intuitive" to use.
- **Please note that since @johannbarbie is not available in the week of the meetup, this issue as special priority to be completed before July 19th, Friday.

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
![Planet A - screen flow (1)](https://user-images.githubusercontent.com/659301/61317128-a8636d00-a802-11e9-9516-f3d03e5e6b97.png)

here are some more details in the mock: https://docs.google.com/drawings/d/1rcTgrE9ZsbClerhOGthGe9J6eLHYrQnq7ZJp8h7mwYs

**Comment by vrde** [comment]
[Unit test](https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkSpendCond.test.js#L1115-L1272) that implements this functionality.

**Comment by johba37** [comment]
**Spec for QR code generation:**

1. query `getUnspent(citizenAddr, passportColor)` and read first passport data as `dataBefore`.
2. update CO2 in passport data as `dataAfter`.
3. create `sig` by `ecsign(hashPersonalMessage(dataBefore, dataAfter), PRIV)`.
4. concatenate `| 2 bytes  passportColor | 20 bytes citizenAddr | 32 bytes dataAfter | 32 bytes sigR | 32 bytes sigS | 1 byte	sigV |`.
5. build URL `https://toco2.leap.rocks/trade#<119 bytes receipt encoded as base64 url (rfc4648)>`.

**Spec for scanning and verifying QR code:**

1. scan URL, extract `passportColor`, `citizenAddr`, `dataAfter` and `sig`.
2. query `getUnspent(citizenAddr, passportColor)`, take first result, read data as `dataBefore`.
3. `ecrecover(hashPersonalMessage(dataBefore, dataAfter))` and compare to `citizenAddr`, should match.
4. use `sig` and `dataAfter` in [transaction payload](https://github.com/social-dist0rtion-protocol/toco2-contracts/blob/master/test/earth.js#L80-L81).
