### ISSUE TITLE
better error handling of failed transactions

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#52]

**Comment by TimDaub** [comment]
Assigned @johannbarbie to garden this issue asap.

**Comment by johba37** [comment]
@vrde do you remember what this was about?

**Comment by TimDaub** [comment]
## Scope

- Take a look to `components/Receipt.js`
- When an error occurs, we potentially have the opportunity to display an error receipt
- At this stage, we only yield a `console.log` however

## Deliverables

- Allow a developer to display a proper error as a receipt

## Roles
bounty gardener: @TimDaub  / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
@vrde and I decided to not claim a bounty for this one.
