### ISSUE TITLE
Create a beautiful and secure paper wallet for EthBerlin and cccamp19

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#54]

**Comment by MaxStalker** [comment]
Guys, if you can provide me the data template - basically JSON with mockup data - I can make a plugin for Figma and design super cool wallets :)

Also, I would like to tackle this one 🐱‍👤

**Comment by TimDaub** [comment]
## Scope

- Every hacker at EthBerlin will get a paper wallet with their passport and some Goellars to start playing the game
- The paper wallet is the first hurdle towards on-boarding into the game. There'll very likely not be an "official" on-boarding ceremony that allow users to get on-boarded directly. This means, the paper wallets will have to have a very high conversion rate
- At previous events, many users irresponsibly discarded their paper wallets on the ground, trash cans or other insecure spots. This allowed malicious actors to swipe these paper wallets and left those that discarded them without a chance to participate
- There's three different teams in Planet A: red, blue and yellow (see ethBerlin website for hex codes: https://ethberlinzwei.com/)
- We're planning to have the passports have the colors of EthBerlin
- Many speakers at EthBerlin have already picked their color by adding their speaker-picture as e.g. their twitter avatar
- Ideally, we then also allow the players of the game to pick their color when they receive their EthBerlin goodie bag at the entrance: "Which team do you want to be on?"

## Deliverables

- Write some code that generates a visually pleasing PDF (ideally 1 page) that:
  - Introduces the player to the game
  - Makes them aware of their color
  - Makes them scan the QR code with their phone
  - Makes them care for their paper wallet (e.g. "last step: rip your paper wallet into pieces such that no one can steal your private key" or "make sure you don't discard this paper wallet in an insecure place", etc.)
- As we'd also like to have the game playable at cccamp19, make sure that you **don't** brand the paper wallet too much to EthBerlin. It'd be good if we could configure some texts and colors or if we just write something that is generic enough for both events. Up to the worker to come up with a concrete solution for this.

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
Payout has been requested. Closing this.
