### ISSUE TITLE
talk to an investor to raise prize money for event

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#58]
give prizes to MP

**Comment by TimDaub** [comment]
## Scope

- Planet A is a game where interesting social dynamics could occur
- Additionally, interesting technical coordination algorithms could emerge, if we'd e.g. incentivize programmers to build dApps to rescue the in game world
- We think that programmers (e.g. at EthBerlin) would be more incentivized to try building an effective coordination dapp though if we offered a price at the end of the hackathon

## Deliverables

- Talk to someone that has money
- Ask them to pay $1000-$5000 into the SDP multisig that we can then use to e.g. fund a gitcoin bounty to incentivize hackers to hack on Planet A

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by TimDaub** [comment]
This is not happening anymore. Closing.
