### ISSUE TITLE
solve old accounting mess

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#59]

**Comment by TimDaub** [comment]
## Scope

- SDP has delivered a demo and presentation for the Ethereum meetup in Berlin
- Given the time constraints of delivering the demo and presentation, account hasn't been done properly and so many contributors have not been paid in SDP tokens

## Deliverables

- Retro-actively solve accounting problem of SDP

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%
