### ISSUE TITLE
Implement receipts for defect and collaborate

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#66]
## Scope

- @vrde has implemented functionality that allows two players witness a successful "defect" or "collaborate" transaction: #68
  - There's more details here: https://github.com/social-dist0rtion-protocol/planet-a/issues/68
- We're still missing receipts for the four outcomes
  - collaborate and collaborate
  - defect and defect
  - collaborate and defect
  - defect and collaborate

## Deliverables

- Build on the branch that was listed above
- Implement views for the above listed scenarios
- Make them dramatic for the player (funny, sad, etc.)

## Note

@vrde has done the required work to get the events in issue #68 

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: worker/ 75%
bounty reviewer: name / 15%

**Comment by vrde** [comment]
Note that since #70 we have events as well.

**Comment by vrde** [comment]
> Note that since #70 we have events as well.

To use events we need to use websockets, but if I try to change `SIDECHAIN.RPC` in `config.js` to connect to `wss://testnet-node1.leapdao.org:1443` we end up with a growing number of connections to the websocket endpoint.

I guess it's a bug in some polling mechanism, where a new connection is created on every loop.

**Comment by vrde** [comment]
I've re-opened #68 :)
