### ISSUE TITLE
Remove unnecessary UI components and adjust wallet information

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#7]
## Scope

- Many UI components from the burner-wallet are not needed for the game and should hence be removed or hidden
- Hiding UI elements has the benefit of having a very small chance of breaking some entangled functionality

Advanced.js
<img width="758" alt="Screen Shot 2019-07-16 at 14 49 33" src="https://user-images.githubusercontent.com/2758453/61295703-f2cff400-a7d8-11e9-901a-06d5cb9eb8b1.png">

"the transaction history"
<img width="772" alt="Screen Shot 2019-07-16 at 14 49 47" src="https://user-images.githubusercontent.com/2758453/61295719-f95e6b80-a7d8-11e9-821f-344112b7b9cd.png">

## Deliverables

- Remove or hide:
  - ~the transaction history in App.js (History.js and RecentTransactions.js)~
  - all links to the "Exchange.js" view. Ideally remove Exchange.js
  - RequestFunds.js and "Request" button in App.js
  - In "Advanced", hide "Display currency" and "Enable advanced features"
  - Adjust "Code" and "About" in "Advanced" (actually make them configurable with config.js and send a PR upstream <3)
  - Adjust `<title />` and all other meta tags/data in index.html

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johba37** [comment]
i think the `history` could be interesting to for players to learn about the dynamics of the different trades. (why did this trade yield more than that trade. plus there is a way to get to the profile of the other players and see their `co2Locked` and `co2Emitted` values).

also: `In the current version of the burner-wallet only the sender is presented with a receipt view. When a trade completes successfully, however, both parties should be prompted with this view`

=> imo should consider keeping the history as a cheap workaround for the initiator of a trade to view receipt.

**Comment by TimDaub** [comment]
> * the transaction history in App.js (History.js and RecentTransactions.js)

removed as discussed in Slack

**Comment by TimDaub** [comment]
Fixed in #13
