### ISSUE TITLE
Create a list of 600 fictitious energy company names and logos

### ISSUE THREAD

**Issue by micheleb** [social-dist0rtion-protocol/planet-a#76]
## Scope

- Players need to be able to easily recognize their entries on the leaderboards
- For the ethereum meetup demo, players were randomly assigned the name of one of the 50 most polluting companies in the world, which was paired with the address of their passport (both by the burner wallet, and by the web dashboard)
- We probably don't have enough time to let players set their name and avatar for their passport before CCC/ethBerlinZwei
- This time we need at least 600 names (which is the total number of ethBerlinZwei attendees)

## Deliverables

- a list (in JSON) of 600+ company names and URLs from which the associated logo can be pulled

## Roles
bounty gardener: @micheleb  / 10%
bounty worker: @micheleb / 75%
bounty reviewer: name / 15%

**Comment by micheleb** [comment]
list available at https://github.com/social-dist0rtion-protocol/planet-a-dashboard/blob/master/names.json

**Comment by TimDaub** [comment]
@micheleb can you take care of requesting a payout?

I'll optimistically close. Feel free to reopen.
