### ISSUE TITLE
migrate wallet to goellars V2

### ISSUE THREAD

**Issue by johba37** [social-dist0rtion-protocol/planet-a#83]
ERC20 deployed as `0x9cfae72c21103033c8fd8a8c6fb02a0ccfe63b5e` on rinkeby.

this token can be collateralized with DAI (Leap on testnet). this will allow:
- to deposit DAI and receive Goellars
- run an exit market maker that returns DAI for Goellar exits.

few things need to happen now:
- deploy new contracts that work with GoelersV2.
- enable all currencies in wallet and bring back exchange button.
- test deposits.
- deploy exit market maker.
- test exits

**Comment by TimDaub** [comment]
Assigned @johannbarbie so that he can coordinate all things that need to happen.

**Comment by johba37** [comment]
related: https://github.com/social-dist0rtion-protocol/planet-a/issues/42

**Comment by johba37** [comment]
unassigned @johannbarbie , because he will focus on contracts and ops.

**Comment by johba37** [comment]
@vrde interested to garden this?

**Comment by TimDaub** [comment]
Step 1 is in #104
