### ISSUE TITLE
Add all 6 colors as passports

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#85]
## Scope

We're gonna add 6 colors for passports:
- The three from EthBerlinZwei website
- And the three from the camp: https://events.ccc.de/2019/07/09/design-release-chaos-communication-camp-2019/

## Deliverables

- Once @johannbarbie has deployed 4 more contracts (2 already existing: USA, USB), add these to the planet-a wallet and give them the colors mentioned above

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by MaxStalker** [comment]
![image](https://user-images.githubusercontent.com/3136647/63384005-a44ce100-c3a6-11e9-95a0-8caa970abb70.png)
New colors are here!

**Comment by TimDaub** [comment]
Fixed in #109
