### ISSUE TITLE
Implement "Plant trees" functionality

### ISSUE THREAD

**Issue by TimDaub** [social-dist0rtion-protocol/planet-a#9]
## Scope

- Players emit CO2 on every trade
- A high global CO2 value, however, is not good for them though as trade yields become less
- Hence, some players might be incentivized to "plant trees" to combat the global CO2 pollution of the "Air"
- Planting a tree reduces the global CO2 value and the player's CO2 balance by X
- But of course, planting trees is not for free. It costs Goellars.
- In that sense, "Plant Trees" is the opposite of "Trade"

Inspiration (picture by @vrde)
![image](https://user-images.githubusercontent.com/2758453/61296371-442cb300-a7da-11e9-8dfa-3d320360e68f.png)

## Deliverables

- Implement a simple "Plant trees" view that allows a player to offset their CO2 balance against Goellars
- Given the time constraints, it can really be as simple as adjusting a slider and clicking a "plant" button

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by vrde** [comment]
We've decided to drop this feature for the meetup.
